// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Block is a top-level page landmark (main, header, section, nav, …).
 * Use for document structure; do not nest Block inside Block.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import { blockClasses } from "./block.shared";
import { resolveTag, TagGroup } from "../../utils/tags";

/**
 * Block renders a resolved landmark element with children.
 */
export type BlockProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "tag"> & {
  tag?: string;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Block: Component<BlockProps> = (props) => {
  const [local, rest] = splitProps(props, ["tag", "class", "className", "children"]);
  const resolvedTagValue = () => resolveTag(local.tag, "div", TagGroup.Layout);
  const cls = () => blockClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} {...rest}>
      {local.children}
    </Dynamic>
  );
};
