// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Label associates visible text with a form control via the for attribute.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { labelClasses } from "./label.shared";

/**
 * Label renders accessible text linked to a control.
 */
export type LabelProps = Omit<JSX.LabelHTMLAttributes<HTMLLabelElement>, "class" | "className" | "children"> & {
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Label: Component<LabelProps> = (props) => {
  const [local, rest] = splitProps(props, ["class", "className", "children"]);
  const cls = () => labelClasses({ className: local.class ?? local.className });
  return (
    <label class={cls() || undefined} {...rest}>
      {local.children}
    </label>
  );
};
