// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * List renders semantic ul, ol, dl, or menu lists with ListItem children.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import { listClasses, listItemClasses } from "./list.shared";
import { eqStr, isSetNum } from "../../utils/expr";
import { resolveTag, TagGroup } from "../../utils/tags";

/**
 * List renders a list container (ul, ol, dl, or menu).
 */
export type ListProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "tag"> & {
  tag?: string;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const List: Component<ListProps> = (props) => {
  const [local, rest] = splitProps(props, ["tag", "class", "className", "children"]);
  const resolvedTagValue = () => resolveTag(local.tag, "ul", TagGroup.List);
  const cls = () => listClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} {...rest}>
      {local.children}
    </Dynamic>
  );
};

/**
 * ListItem renders one li with optional value attribute.
 */
export type ListItemProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "tag" | "value"> & {
  tag?: string;
  value?: number;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const ListItem: Component<ListItemProps> = (props) => {
  const [local, rest] = splitProps(props, ["tag", "value", "class", "className", "children"]);
  const resolvedTagValue = () => resolveTag(local.tag, "li", TagGroup.ListItem);
  const cls = () => listItemClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} value={(isSetNum(local.value) && eqStr(resolvedTagValue(), "li")) ? String(local.value ?? 0) : undefined} {...rest}>
      {local.children}
    </Dynamic>
  );
};
