// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Textarea is a multi-line native text field with row sizing.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { textareaClasses, type TextareaSize, type TextareaVariant } from "./textarea.shared";
import { isSetNum } from "../../utils/expr";

/**
 * Textarea renders a styled multi-line form control.
 */
export type TextareaProps = Omit<JSX.TextareaHTMLAttributes<HTMLTextAreaElement>, "class" | "className" | "children" | "variant" | "size" | "value" | "rows" | "disabled" | "required"> & {
  variant?: TextareaVariant;
  size?: TextareaSize;
  value?: string;
  rows?: number;
  disabled?: boolean;
  required?: boolean;
  class?: string;
  className?: string;
};

export const Textarea: Component<TextareaProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "value", "rows", "disabled", "required", "class", "className"]);
  const cls = () => textareaClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <textarea class={cls() || undefined} rows={(isSetNum(local.rows) ? local.rows : 4)} disabled={local.disabled || undefined} required={local.required || undefined} {...rest} value={(local.value) ?? ""} />
  );
};
