// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Stack arranges children vertically in a flex column.
 * Default layout primitive for spacing sections and form fields.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import { stackClasses } from "./stack.shared";
import { resolveTag, TagGroup } from "../../utils/tags";

/**
 * Stack renders a vertical flex container.
 */
export type StackProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "tag"> & {
  tag?: string;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Stack: Component<StackProps> = (props) => {
  const [local, rest] = splitProps(props, ["tag", "class", "className", "children"]);
  const resolvedTagValue = () => resolveTag(local.tag, "div", TagGroup.Stack);
  const cls = () => stackClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} {...rest}>
      {local.children}
    </Dynamic>
  );
};
