// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Input is a single-line native text field.
 * Supports types, validation attrs, and wireframe variant/size classes.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { inputClasses, type InputSize, type InputVariant } from "./input.shared";
import { defaultIfEmpty } from "../../utils/expr";

/**
 * Input renders a styled single-line form control.
 */
export type InputProps = Omit<JSX.InputHTMLAttributes<HTMLInputElement>, "class" | "className" | "children" | "variant" | "size" | "type" | "disabled" | "required"> & {
  variant?: InputVariant;
  size?: InputSize;
  type?: string;
  disabled?: boolean;
  required?: boolean;
  class?: string;
  className?: string;
};

export const Input: Component<InputProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "type", "disabled", "required", "class", "className"]);
  const cls = () => inputClasses({ variant: local.variant, size: local.size, className: local.class ?? local.className });
  return (
    <input type={defaultIfEmpty(local.type, "text")} class={cls() || undefined} disabled={local.disabled || undefined} required={local.required || undefined} {...rest} />
  );
};
