// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Text renders a paragraph of body copy. Use Inline for inline span copy
 * and Title (as 1–6) for headings.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { textClasses } from "./text.shared";

/**
 * Text renders a p element with body copy classes.
 */
export type TextProps = Omit<JSX.HTMLAttributes<HTMLParagraphElement>, "class" | "className" | "children"> & {
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Text: Component<TextProps> = (props) => {
  const [local, rest] = splitProps(props, ["class", "className", "children"]);
  const cls = () => textClasses({ className: local.class ?? local.className });
  return (
    <p class={cls() || undefined} {...rest}>
      {local.children}
    </p>
  );
};
