// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Icon renders a class-based span, svg use reference, or text fallback.
 * Decorative icons are hidden from assistive technology by default.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { iconClasses, type IconSize } from "./icon.shared";
import { eqStr, isSetStr, oneOfOr, orUndef } from "../../utils/expr";

/**
 * Icon renders a class-based span, svg use, or text fallback host.
 */
export type IconProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "name" | "type" | "baseClass" | "prefix" | "size" | "href" | "title" | "aria-label" | "decorative"> & {
  name?: string;
  type?: string;
  baseClass?: string;
  prefix?: string;
  size?: IconSize;
  href?: string;
  title?: string;
  "aria-label"?: string;
  decorative?: boolean;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Icon: Component<IconProps> = (props) => {
  const [local, rest] = splitProps(props, ["name", "type", "baseClass", "prefix", "size", "href", "title", "aria-label", "decorative", "class", "className", "children"]);
  const iconKindValue = () => oneOfOr(local.type, "class", "svg", "text");
  const isDecorativeValue = () => (local.decorative || (!(isSetStr(local.title)) && !(isSetStr(local["aria-label"]))));
  const cls = () => iconClasses({ type: local.type, size: local.size, baseClass: local.baseClass, name: local.name, prefix: local.prefix, className: local.class ?? local.className });
  return (
    eqStr(iconKindValue(), "svg") ? (
      <svg class={cls() || undefined} aria-hidden={isDecorativeValue() ? "true" : undefined} role={!(isDecorativeValue()) ? "img" : undefined} aria-label={(!(isDecorativeValue()) && isSetStr(local["aria-label"])) ? local["aria-label"] : undefined} {...rest}>
        {isSetStr(local.title) ? (
          <title>
            {local.title}
          </title>
        ) : null}
        {isSetStr(local.href) ? (
          <use href={orUndef(local.href)} />
        ) : null}
        {local.children}
      </svg>
    ) : (
      eqStr(iconKindValue(), "text") ? (
        <span class={cls() || undefined} aria-hidden={isDecorativeValue() ? "true" : undefined} role={!(isDecorativeValue()) ? "img" : undefined} aria-label={(!(isDecorativeValue()) && isSetStr(local["aria-label"])) ? local["aria-label"] : undefined} {...rest}>
          {local.children}
        </span>
      ) : (
        <span class={cls() || undefined} aria-hidden={isDecorativeValue() ? "true" : undefined} role={!(isDecorativeValue()) ? "img" : undefined} aria-label={(!(isDecorativeValue()) && isSetStr(local["aria-label"])) ? local["aria-label"] : undefined} {...rest} />
      )
    )
  );
};
