// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Title renders a heading (h1–h6) from As (1–6). Defaults to h2 when As is 0
 * or out of range.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import { titleClasses } from "./title.shared";
import { titleTag } from "../../utils/expr";

/**
 * Title renders the resolved heading element.
 */
export type TitleProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "as"> & {
  as?: 1 | 2 | 3 | 4 | 5 | 6;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Title: Component<TitleProps> = (props) => {
  const [local, rest] = splitProps(props, ["as", "class", "className", "children"]);
  const resolvedTagValue = () => titleTag(local.as);
  const cls = () => titleClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} {...rest}>
      {local.children}
    </Dynamic>
  );
};
