// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Box is a generic layout wrapper for internal sections.
 * Not for top-level landmarks — use Block for page regions.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { Dynamic } from "solid-js/web";
import { boxClasses } from "./box.shared";
import { resolveTag, TagGroup } from "../../utils/tags";

/**
 * Box renders a div layout wrapper.
 */
export type BoxProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "tag"> & {
  tag?: string;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Box: Component<BoxProps> = (props) => {
  const [local, rest] = splitProps(props, ["tag", "class", "className", "children"]);
  const resolvedTagValue = () => resolveTag(local.tag, "div", TagGroup.BoxAllowed);
  const cls = () => boxClasses({ className: local.class ?? local.className });
  return (
    <Dynamic component={resolvedTagValue()} class={cls() || undefined} {...rest}>
      {local.children}
    </Dynamic>
  );
};
