// Code generated by @ui8kit/codegen. DO NOT EDIT.
/**
 * Button triggers an action on click.
 * Optional Href renders an anchor with button appearance (CTA navigation).
 * For exotic roots, use ButtonClasses (Templ/Svelte/Vue/Solid) or asChild (React).
 * Prefer Link for prose/semantic navigation.
 */

import { splitProps, type JSX, type Component } from "solid-js";
import { buttonClasses, type ButtonSize, type ButtonVariant } from "./button.shared";
import { eqStr, isSetStr, oneOfOr, orUndef } from "../../utils/expr";

/**
 * Button renders a button element, or an anchor when Href is set.
 * Type/Form apply only in button mode; Disabled on anchors uses aria-disabled.
 */
export type ButtonProps = Omit<JSX.HTMLAttributes<HTMLElement>, "class" | "className" | "children" | "variant" | "size" | "type" | "href" | "target" | "rel" | "external" | "disabled"> & {
  variant?: ButtonVariant;
  size?: ButtonSize;
  type?: string;
  href?: string;
  target?: string;
  rel?: string;
  external?: boolean;
  disabled?: boolean;
  class?: string;
  className?: string;
  children?: JSX.Element;
};

export const Button: Component<ButtonProps> = (props) => {
  const [local, rest] = splitProps(props, ["variant", "size", "type", "href", "target", "rel", "external", "disabled", "class", "className", "children"]);
  const targetValue = () => (isSetStr(local.target) ? local.target : (local.external ? "_blank" : ""));
  const relValue = () => (isSetStr(local.rel) ? local.rel : ((local.external || eqStr(targetValue(), "_blank")) ? "noopener noreferrer" : ""));
  const cls = () => buttonClasses({ variant: local.variant, size: local.size, disabled: local.disabled, className: local.class ?? local.className });
  return (
    isSetStr(local.href) ? (
      <a href={orUndef(local.href)} class={cls() || undefined} target={orUndef(targetValue())} rel={orUndef(relValue())} aria-disabled={local.disabled ? "true" : undefined} tabIndex={local.disabled ? -1 : undefined} {...rest}>
        {local.children}
      </a>
    ) : (
      <button type={oneOfOr(local.type, "button", "submit", "reset")} class={cls() || undefined} disabled={local.disabled || undefined} {...rest}>
        {local.children}
      </button>
    )
  );
};
